name: Deploy Next.js App to Azure App Service (ZIP)

on:
  push:
    branches:
      - frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Copy necessary files for deployment
        run: |
          mkdir deploy
          cp -r .next deploy/.next
          cp -r public deploy/public
          cp -r node_modules deploy/node_modules
          cp -r package.json deploy/
          cp -r next.config.js deploy/ || true
          cp -r next.config.ts deploy/ || true

      - name: Create deployment zip
        run: |
          cd deploy
          zip -r ../deploy.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-step4-45
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy.zip
